#!/bin/bash

# ========================================
# Automated Deployment Script
# ========================================
# This script automates the entire deployment process:
# 1. Terraform initialization and apply
# 2. Inventory update
# 3. Ansible playbook execution
# 4. Verification

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"
ANSIBLE_DIR="$PROJECT_ROOT/ansible"
EVIDENCE_DIR="$PROJECT_ROOT/evidence"
KEYS_DIR="$PROJECT_ROOT/keys"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Terraform + Ansible Deployment${NC}"
echo -e "${BLUE}========================================${NC}\n"

# ========================================
# Step 1: Prerequisites Check
# ========================================
echo -e "${YELLOW}[1/8] Checking prerequisites...${NC}"

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: Terraform is not installed${NC}"
    exit 1
fi

if ! command -v ansible &> /dev/null; then
    echo -e "${RED}Error: Ansible is not installed${NC}"
    exit 1
fi

if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: AWS CLI is not installed${NC}"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS credentials not configured${NC}"
    echo -e "${YELLOW}Run: aws configure${NC}"
    exit 1
fi

echo -e "${GREEN}✓ All prerequisites met${NC}\n"

# ========================================
# Step 2: Terraform Initialization
# ========================================
echo -e "${YELLOW}[2/8] Initializing Terraform...${NC}"
cd "$TERRAFORM_DIR"

terraform init
terraform validate

echo -e "${GREEN}✓ Terraform initialized${NC}\n"

# ========================================
# Step 3: Terraform Apply
# ========================================
echo -e "${YELLOW}[3/8] Provisioning infrastructure with Terraform...${NC}"

terraform plan

echo -e "${YELLOW}Below are the resources that will be created:${NC}"
grep -E '^  #|^    +' "$EVIDENCE_DIR/PLAN.txt" | sed 's/^  #/Resource:/;s/^    /    Details: /'

# ========================================
# Step 4: User Approval Before Apply
# ========================================
echo -e "${YELLOW}Do you want to proceed with these changes? (yes/no)${NC}"
read -r USER_APPROVE
if [[ ! "$USER_APPROVE" =~ ^[Yy][Ee][Ss]$ ]]; then
    echo -e "${RED}Aborting deployment as per user request.${NC}"
    exit 1
fi

# ========================================
# Step 5: Terraform Apply
# ========================================
echo -e "${BLUE}Applying Terraform configuration...${NC}"
terraform apply -auto-approve | tee "$EVIDENCE_DIR/APPLY.txt"

echo -e "${GREEN}✓ Infrastructure provisioned${NC}\n"

# ========================================
# Step 4: Extract Outputs
# ========================================
echo -e "${YELLOW}[4/8] Extracting Terraform outputs...${NC}"

PUBLIC_IP=$(terraform output -raw instance_public_ip)
SSH_KEY_PATH=$(terraform output -raw ssh_private_key_path)
SSH_USER=$(terraform output -raw ssh_user)

echo -e "${BLUE}Instance Public IP: ${GREEN}$PUBLIC_IP${NC}"
echo -e "${BLUE}SSH User: ${GREEN}$SSH_USER${NC}"
echo -e "${BLUE}SSH Key: ${GREEN}$SSH_KEY_PATH${NC}\n"

# ========================================
# Step 5: Update Ansible Inventory
# ========================================
echo -e "${YELLOW}[5/8] Updating Ansible inventory...${NC}"

cd "$ANSIBLE_DIR"

# Backup existing inventory
if [ -f inventory.ini ]; then
    cp inventory.ini inventory.ini.bak
fi

# Create new inventory
cat > inventory.ini <<EOF
# ========================================
# Ansible Inventory Configuration
# ========================================
# Auto-generated by deploy.sh script

[webservers]
$PUBLIC_IP ansible_user=$SSH_USER ansible_ssh_private_key_file=$SSH_KEY_PATH

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
EOF

echo -e "${GREEN}✓ Inventory updated${NC}\n"

# ========================================
# Step 6: Wait for Instance to be Ready
# ========================================
echo -e "${YELLOW}[6/8] Waiting for EC2 instance to be ready...${NC}"

MAX_ATTEMPTS=12
ATTEMPT=0

while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
    if ansible -i inventory.ini webservers -m ping &> /dev/null; then
        echo -e "${GREEN}✓ Instance is ready${NC}\n"
        break
    fi
    
    ATTEMPT=$((ATTEMPT + 1))
    echo -e "${BLUE}Waiting... (attempt $ATTEMPT/$MAX_ATTEMPTS)${NC}"
    sleep 10
done

if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
    echo -e "${RED}Error: Instance not responding after $((MAX_ATTEMPTS * 10)) seconds${NC}"
    exit 1
fi

# ========================================
# Step 7: Run Ansible Playbook
# ========================================
echo -e "${YELLOW}[7/8] Running Ansible playbook...${NC}"

ansible-playbook -i inventory.ini site.yml

echo -e "${GREEN}✓ Ansible configuration complete${NC}\n"

# ========================================
# Step 8: Verification
# ========================================
echo -e "${YELLOW}[8/8] Verifying deployment...${NC}"

WEB_URL="http://$PUBLIC_IP"

echo -e "${BLUE}Testing web server...${NC}"
if curl -s -o /dev/null -w "%{http_code}" "$WEB_URL" | grep -q "200"; then
    echo -e "${GREEN}✓ Web server is responding${NC}\n"
else
    echo -e "${RED}Warning: Web server returned non-200 status${NC}\n"
fi

# ========================================
# Deployment Summary
# ========================================
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Deployment Completed Successfully!${NC}"
echo -e "${GREEN}========================================${NC}\n"

echo -e "${BLUE}Access your web application:${NC}"
echo -e "${GREEN}  URL: $WEB_URL${NC}\n"

echo -e "${BLUE}SSH into the instance:${NC}"
echo -e "${GREEN}  ssh -i $SSH_KEY_PATH $SSH_USER@$PUBLIC_IP${NC}\n"

echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Open ${GREEN}$WEB_URL${NC} in your browser"
echo -e "  2. Take a screenshot and save to ${GREEN}evidence/webpage-screenshot.png${NC}"
echo -e "  3. Run ${GREEN}./scripts/cleanup.sh${NC} to destroy resources when done\n"

echo -e "${BLUE}Evidence files:${NC}"
echo -e "  - ${GREEN}$EVIDENCE_DIR/APPLY.txt${NC} (Terraform apply output)"
echo -e "  - ${GREEN}$EVIDENCE_DIR/webpage-screenshot.png${NC} (Take manually)\n"
