#!/bin/bash

# ========================================
# Update Ansible Inventory Script
# ========================================
# This script updates the Ansible inventory with the EC2 public IP from Terraform outputs

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"
ANSIBLE_DIR="$PROJECT_ROOT/ansible"

echo -e "${BLUE}Updating Ansible inventory...${NC}\n"

cd "$TERRAFORM_DIR"

# Check if Terraform state exists
if [ ! -f terraform.tfstate ]; then
    echo -e "${YELLOW}Error: Terraform state not found. Run 'terraform apply' first.${NC}"
    exit 1
fi

# Extract outputs
PUBLIC_IP=$(terraform output -raw instance_public_ip)
SSH_KEY_PATH=$(terraform output -raw ssh_private_key_path)
SSH_USER=$(terraform output -raw ssh_user)

echo -e "${BLUE}Retrieved from Terraform:${NC}"
echo -e "  Public IP: ${GREEN}$PUBLIC_IP${NC}"
echo -e "  SSH User: ${GREEN}$SSH_USER${NC}"
echo -e "  SSH Key: ${GREEN}$SSH_KEY_PATH${NC}\n"

# Update inventory
cd "$ANSIBLE_DIR"

cat > inventory.ini <<EOF
# ========================================
# Ansible Inventory Configuration
# ========================================
# Auto-generated by update-inventory.sh script

[webservers]
$PUBLIC_IP ansible_user=$SSH_USER ansible_ssh_private_key_file=$SSH_KEY_PATH

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
EOF

echo -e "${GREEN}✓ Inventory updated successfully${NC}\n"

# Test connection
echo -e "${BLUE}Testing connection...${NC}"
if ansible -i inventory.ini webservers -m ping; then
    echo -e "\n${GREEN}✓ Connection successful${NC}\n"
else
    echo -e "\n${YELLOW}Warning: Connection test failed. The instance might still be initializing.${NC}\n"
fi
